### ISSUE TITLE
Unused variable in sampling

### ISSUE THREAD

**Issue by JoeHut** [twairball/keras_lstm_vae#1]
Is there a reason you compute a normal distributed tensor as your epsilon in the sampling Lambda, but actually use the epsilon value given as argument? Doesn't this go against the idea of the VAE?

**Comment by twairball** [comment]
Hey thanks for the comment, you're right that line is redundant. `z` is normal distributed based on `z_mean` and `z_log_sigma`. Have I got it wrong?

**Comment by pyni** [comment]
def sampling(args):
        z_mean, z_log_sigma = args
        epsilon = K.random_normal(shape=(batch_size, latent_dim),
                                  mean=0., stddev=epsilon_std)
        return z_mean + K.exp(z_log_sigma) * epsilon_std

here i think, 'return z_mean + K.exp(z_log_sigma) * epsilon_std'
may be replaced by 'return z_mean + K.exp(z_log_sigma) * epsilon'.
Otherwise  this is not a Gaussian sampling.

**Comment by pyni** [comment]
or like this?:
  def sampling(args):
        z_mean, z_log_sigma = args
        epsilon = K.random_normal(shape=(batch_size, latent_dim),
                                  mean=z_mean, stddev=epsilon_std)
        return z_mean +  (z_log_sigma) * epsilon
![image](https://user-images.githubusercontent.com/18031767/33133153-d29e276e-cfd6-11e7-9592-d3fc5c895962.png)
this is yours.

![image](https://user-images.githubusercontent.com/18031767/33133176-ec7c8b58-cfd6-11e7-87e6-e2354f2bfa74.png)
this is the changed version.

**Comment by twairball** [comment]
Yes! thanks for the clarification. Please send PR?

**Comment by pyni** [comment]
I'm not sure.
Maybe it should be like this:
        z_mean, z_log_sigma = args
        epsilon = K.random_normal(shape=(batch_size, latent_dim),
                                 mean=0, stddev=epsilon_std)                   
        return z_mean +   z_log_sigma * epsilon
