### ISSUE TITLE
Input type

### ISSUE THREAD

**Issue by hkmztrk** [twairball/keras_lstm_vae#3]
Hello,

How can I use my own data, which contains categoric encoded sequences of length 1000?
(e.g. one sample of sequence is represented like this [1, 23, 6, 12, 4, 0, 0, 0 ...] )
And how should I decide the time step?

Thanks in advance!

**Comment by twairball** [comment]
If its categoric then you'll need to represent as embeddings. 
Ref: https://keras.io/layers/embeddings/

As for time step, I would recommend starting with e.g. k=3, and just try it out :)

**Comment by hkmztrk** [comment]
Hello again,

I couldn't find a time to actually work on this model and came back now, and I'm sorry if this is a trivial question: Your data has the following shape,

    data = np.fromfile('sample_data.dat').reshape(419,13)

So what do this shape (419,13) represent? How should I model my data? For instance would the following method alright?

	XInput = Input(shape=(1000, ))
	encode = Embedding(input_dim=24, output_dim=128)(XInput)

**Comment by twairball** [comment]
Hi - the shape (419,13) is just the shape of the original dataset, which i saved to a flat `.dat` file.
